version: '3'

services:
  server:
    container_name: server
    build:
      context: ./src/cepheus_interface/server/
      dockerfile: Dockerfile
    image: server
    restart: unless-stopped
    volumes:
      - ./src/cepheus_interface/server:/app
    ports:
      - "9000:9000"

  web_ui:
    container_name: web_ui
    build:
      context: ./src/cepheus_interface/web_ui/
      dockerfile: Dockerfile
    image: web_ui
    restart: unless-stopped
    depends_on:
      - server
    volumes:
      - ./src/cepheus_interface/web_ui:/app
    ports:
      - "80:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
